---
description: Pipeline for processing GitHub Advisory Database.
processors:
  - set:
      field: ecs.version
      tag: set_ecs_version
      value: 8.11.0
  - fail:
      tag: cel_failure
      if: ctx.error?.message != null && ctx.message == null && ctx.event?.original == null
      message: error message set and no data to process
  - set:
      field: event.kind
      tag: set_event_kind_1
      value: enrichment
  - append:
      field: event.category
      tag: append_event_catgeory
      value: vulnerability
      allow_duplicates: false
  - append:
      field: event.type
      tag: append_event_type
      value: info
      allow_duplicates: false
  - json:
      field: message
      tag: json_message
      target_field: github_advisory_database.vulnerability
      on_failure:
        - append:
            field: error.message
            value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
#   - rename:
#       field: json.cve_id
#       tag: rename_cve_id
#       target_field: github_advisory_database.vulnerability
  - remove:
      tag: remove_json
      field:
        - json
        - message
      ignore_missing: true
on_failure:
  - append:
      field: error.message
      value: 'Processor {{{_ingest.on_failure_processor_type}}} with tag {{{_ingest.on_failure_processor_tag}}} in pipeline {{{_ingest.pipeline}}} failed with message: {{{_ingest.on_failure_message}}}'
  - set:
      field: event.kind
      value: pipeline_error
