services:
  projectdiscovery_cloud-projectdiscovery_cloud-mock:
    image: docker.elastic.co/observability/stream:v0.20.0
    hostname: projectdiscovery_cloud-projectdiscovery_cloud-mock
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config-projectdiscovery_cloud.yml
