services:
  projectdiscovery-cloud-vulnerability-scan:
    image: docker.elastic.co/observability/stream:v0.20.0
    hostname: projectdiscovery-cloud-vulnerability-scan
    ports:
      - 8090
    volumes:
      - ./files:/files:ro
    environment:
      PORT: '8090'
    command:
      - http-server
      - --addr=:8090
      - --config=/files/config-vulnerability_scan.yml
